"""Add batch_number column

Revision ID: 8cf202c7ede7
Revises: 6648e6648433
Create Date: 2024-11-24 19:19:31.302182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf202c7ede7'
down_revision = '6648e6648433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_number', sa.String(length=36), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_column('batch_number')

    # ### end Alembic commands ###
