"""Add vaccination model

Revision ID: f6f034a20640
Revises: 8cf202c7ede7
Create Date: 2024-11-26 14:49:29.196928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6f034a20640'
down_revision = '8cf202c7ede7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccination',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.alter_column('batch_number',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.alter_column('batch_number',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)

    op.drop_table('vaccination')
    # ### end Alembic commands ###
